frase=('Curso em Video Python')
a=len(frase)
b=frase.count('u')
c=frase.find('deo')
d='Curso' in frase
e=frase.replace('Python', 'Android')
f=frase.upper() #lower tudo minusculo e #capitalize primeira palavra maiúscula #Title todas as palavras com a primeira em maiuscula
g=frase.split()
print(frase)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(g[3])