a=input("Digite algo :")
print("O tipo primitivo desse valor é:")
print(a.islower())
print(a.isascii())
print(a.isalpha())
print(a.isalnum())
print(a.isprintable())
print(a.isdecimal())
print(a.islower())
